services:
  open-webui:
    container_name: open-webui
    environment:
      AIOHTTP_CLIENT_TIMEOUT: 600
      ENABLE_CODE_EXECUTION: false
      ENABLE_CODE_INTERPRETER: false
      ENABLE_OLLAMA_API: false
      ENABLE_SIGNUP_PASSWORD_CONFIRMATION: true
      OPENAI_API_BASE_URL: http://vllm:8000/v1
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD-SHELL
      - python -c "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"
        || exit 1
      timeout: 10s
    image: ghcr.io/open-webui/open-webui
    restart: always
  vllm:
    command: |-
      sh -c "
      cat > /etc/nginx/nginx.conf << EOF
      events {
          worker_connections 1024;
      }

      http {
          server {
              listen 8000;
              server_name localhost;
              location / {
                  proxy_pass \$VLLM_API_BASE_URL/;
                  proxy_ssl_server_name on;
                  proxy_ssl_verify off;
                  proxy_set_header Authorization \"Bearer \$$VLLM_API_KEY\";
                  proxy_set_header X-Real-IP \\\$$remote_addr;
                  proxy_set_header X-Forwarded-For \\\$$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \\\$$scheme;

                  proxy_connect_timeout 600s;
                  proxy_send_timeout 600s;
                  proxy_read_timeout 600s;

                  proxy_buffering off;
                  proxy_cache off;
              }
          }

          server {
              listen 3000;
              server_name localhost;

              location /v1/models {
                  rewrite ^/v1/models /api/models break;
                  proxy_set_header Host \\\$$host;
                  proxy_set_header X-Real-IP \\\$$remote_addr;
                  proxy_set_header X-Forwarded-For \\\$$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \\\$$scheme;
                  proxy_pass http://open-webui:8080;
              }

              location /v1/chat/completions {
                  rewrite ^/v1/chat/completions /api/chat/completions break;
                  proxy_set_header Host \\\$$host;
                  proxy_set_header X-Real-IP \\\$$remote_addr;
                  proxy_set_header X-Forwarded-For \\\$$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \\\$$scheme;
                  proxy_pass http://open-webui:8080;
              }

              location /v1/attestation/ {
                  if (\\\$$request_method = 'OPTIONS') {
                      add_header 'Access-Control-Allow-Origin' '*' always;
                      add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
                      add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
                      add_header 'Access-Control-Max-Age' 1728000 always;
                      add_header 'Content-Type' 'text/plain; charset=utf-8' always;
                      add_header 'Content-Length' 0 always;
                      return 204;
                  }

                  add_header 'Access-Control-Allow-Origin' '*' always;
                  add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
                  add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
                  add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

                  proxy_pass \$VLLM_API_BASE_URL/v1/attestation/;
                  proxy_ssl_server_name on;
                  proxy_ssl_verify off;
                  proxy_set_header Authorization \"Bearer \$$VLLM_API_KEY\";
                  proxy_set_header X-Real-IP \\\$$remote_addr;
                  proxy_set_header X-Forwarded-For \\\$$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \\\$$scheme;
                  proxy_buffering off;
                  proxy_cache off;
              }

              location /v1/signature/ {
                  if (\\\$$request_method = 'OPTIONS') {
                      add_header 'Access-Control-Allow-Origin' '*' always;
                      add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
                      add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
                      add_header 'Access-Control-Max-Age' 1728000 always;
                      add_header 'Content-Type' 'text/plain; charset=utf-8' always;
                      add_header 'Content-Length' 0 always;
                      return 204;
                  }

                  add_header 'Access-Control-Allow-Origin' '*' always;
                  add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
                  add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
                  add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

                  proxy_pass \$VLLM_API_BASE_URL/v1/signature/;
                  proxy_ssl_server_name on;
                  proxy_ssl_verify off;
                  proxy_set_header Authorization \"Bearer \$$VLLM_API_KEY\";
                  proxy_set_header X-Forwarded-For \\\$$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \\\$$scheme;
                  proxy_buffering off;
                  proxy_cache off;
              }

              location / {
                  proxy_pass http://open-webui:8080/;
                  proxy_set_header Host \\\$$host;
                  proxy_set_header X-Real-IP \\\$$remote_addr;
                  proxy_set_header X-Forwarded-For \\\$$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \\\$$scheme;

                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \\\$$http_upgrade;
                  proxy_set_header Connection "upgrade";

                  proxy_connect_timeout 600s;
                  proxy_send_timeout 600s;
                  proxy_read_timeout 600s;

                  proxy_buffering off;
                  proxy_cache off;
              }
          }
      }
      EOF
      nginx -g 'daemon off;'
      "
    container_name: vllm
    depends_on:
      open-webui:
        condition: service_healthy
    environment:
      VLLM_API_BASE_URL: ${VLLM_API_BASE_URL}
      VLLM_API_KEY: ${VLLM_API_KEY}
    image: nginx:alpine
    ports:
    - 3000:3000
    restart: always
volumes: {}

